/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpus_apl;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author KANIA
 */
public class fromPinjam extends javax.swing.JDialog {
    private DefaultTableModel tabmode;
    
    private void tampil_IDAnggota(){
        Object[]baris={"ID Anggota","Nama Anggota"};
        tabmode = new DefaultTableModel(null,baris);
        id_Anggota.setModel(tabmode);
        String sql = "Select ID_Anggota, Nama_Anggota from anggota order by ID_Anggota asc";
      
        try{
            Connection konek= new koneksi_mysql().getConnection();
            Statement stat = konek.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){ 
                String ID_Anggota = hasil.getString("ID_Anggota");
                String Nama_Anggota = hasil.getString("Nama_Anggota");
                
                String[]data={ID_Anggota, Nama_Anggota};
                tabmode.addRow(data);
            }
            hasil.close();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Data Gagal", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
        }
     private void tampil_IDPetugas(){
        Object[]baris={"ID Petugas","Nama Petugas"};
        tabmode = new DefaultTableModel(null,baris);
        id_petugas.setModel(tabmode);
        String sql = "Select ID_Petugas, Nama_Petugas from petugas order by ID_Petugas asc";
      
        try{
            Connection konek= new koneksi_mysql().getConnection();
            Statement stat = konek.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){ 
                String ID_Petugas = hasil.getString("ID_Petugas");
                String Nama_Petugas= hasil.getString("Nama_Petugas");
                
                String[]data={ID_Petugas, Nama_Petugas};
                tabmode.addRow(data);
            }
            hasil.close();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Data Gagal", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
        }
      private void tampil_IDBuku(){
        Object[]baris={"ID Buku","Judul Buku"};
        tabmode = new DefaultTableModel(null,baris);
        id_buku.setModel(tabmode);
        String sql = "Select ID_Buku, Judul_Buku from buku order by ID_Buku asc";
      
        try{
            Connection konek= new koneksi_mysql().getConnection();
            Statement stat = konek.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){ 
                String ID_Buku = hasil.getString("ID_Buku");
                String Judul_Buku = hasil.getString("Judul_Buku");
                
                String[]data={ID_Buku, Judul_Buku};
                tabmode.addRow(data);
            }
            hasil.close();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Data Gagal", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
        }
    /**
     * Creates new form fromAnggota
     */
    public fromPinjam(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tampil_IDAnggota();
        tampil_IDPetugas();
        tampil_IDBuku();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jMenu6 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TanggalPinjam = new javax.swing.JTextField();
        IdBuku = new javax.swing.JTextField();
        IdAnggota = new javax.swing.JTextField();
        IdPetugas = new javax.swing.JTextField();
        BtnSimpanData = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        id_Anggota = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        id_petugas = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        id_buku = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        BulanPinjam = new javax.swing.JTextField();
        TahunPinjam = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("jCheckBoxMenuItem3");

        jMenu1.setText("jMenu1");

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        jMenu6.setText("jMenu6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 153));

        jLabel1.setBackground(new java.awt.Color(153, 0, 0));
        jLabel1.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FROM PEMINJAMAN BUKU");
        jLabel1.setOpaque(true);

        jLabel3.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel3.setText("*ID_Petugas ");

        jLabel5.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel5.setText("*ID_Anggota");

        jLabel7.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel7.setText("*ID_Buku");

        jLabel8.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel8.setText("*Tanggal Pinjam");

        TanggalPinjam.setBackground(new java.awt.Color(255, 255, 204));
        TanggalPinjam.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        TanggalPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanggalPinjamActionPerformed(evt);
            }
        });

        IdBuku.setBackground(new java.awt.Color(255, 255, 204));
        IdBuku.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        IdBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdBukuActionPerformed(evt);
            }
        });

        IdAnggota.setBackground(new java.awt.Color(255, 255, 204));
        IdAnggota.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N

        IdPetugas.setBackground(new java.awt.Color(255, 255, 204));
        IdPetugas.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N

        BtnSimpanData.setBackground(new java.awt.Color(255, 255, 255));
        BtnSimpanData.setText("Simpan Data");
        BtnSimpanData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanDataActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calisto MT", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 51));
        jLabel6.setText("*Wajib Disi");

        jLabel13.setBackground(new java.awt.Color(153, 0, 0));
        jLabel13.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 204));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("ID Petugas");
        jLabel13.setOpaque(true);

        id_Anggota.setBackground(new java.awt.Color(255, 255, 204));
        id_Anggota.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        id_Anggota.setForeground(new java.awt.Color(102, 0, 0));
        id_Anggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        id_Anggota.setGridColor(new java.awt.Color(153, 0, 0));
        jScrollPane1.setViewportView(id_Anggota);

        id_petugas.setBackground(new java.awt.Color(255, 255, 204));
        id_petugas.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        id_petugas.setForeground(new java.awt.Color(102, 0, 0));
        id_petugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        id_petugas.setGridColor(new java.awt.Color(153, 0, 0));
        jScrollPane2.setViewportView(id_petugas);

        jLabel15.setBackground(new java.awt.Color(153, 0, 0));
        jLabel15.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 204));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("ID Anggota");
        jLabel15.setOpaque(true);

        jLabel16.setBackground(new java.awt.Color(153, 0, 0));
        jLabel16.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 204));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("ID Buku");
        jLabel16.setOpaque(true);

        id_buku.setBackground(new java.awt.Color(255, 255, 204));
        id_buku.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        id_buku.setForeground(new java.awt.Color(102, 0, 0));
        id_buku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        id_buku.setGridColor(new java.awt.Color(153, 0, 0));
        jScrollPane3.setViewportView(id_buku);

        jLabel9.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel9.setText("*Bulan Pinjam");

        BulanPinjam.setBackground(new java.awt.Color(255, 255, 204));
        BulanPinjam.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        BulanPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BulanPinjamActionPerformed(evt);
            }
        });

        TahunPinjam.setBackground(new java.awt.Color(255, 255, 204));
        TahunPinjam.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        TahunPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TahunPinjamActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel11.setText("*Tahun Pinjam");

        jLabel12.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel12.setText("Tanggal Kembali      :");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel8))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TanggalPinjam)
                                        .addComponent(IdPetugas)
                                        .addComponent(IdAnggota)
                                        .addComponent(IdBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel9)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(25, 25, 25)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TahunPinjam)
                                        .addComponent(BulanPinjam))))
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(BtnSimpanData))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel13, jLabel15, jLabel16, jScrollPane1, jScrollPane2, jScrollPane3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(IdPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(IdAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(IdBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(TanggalPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(BulanPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(TahunPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(BtnSimpanData)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel6)))
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TanggalPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanggalPinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TanggalPinjamActionPerformed

    private void IdBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdBukuActionPerformed

    private void BtnSimpanDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanDataActionPerformed
        
        try{
            Tanggal pinjam = new Tanggal(Integer.parseInt(TanggalPinjam.getText()),Integer.parseInt(BulanPinjam.getText()),Integer.parseInt(TahunPinjam.getText()));
            Tanggal kembali = new Tanggal(pinjam.getHari()+7,pinjam.getBulan(),pinjam.getTahun());
            
            Class.forName("com.mysql.jdbc.Driver");
            String sql = "Select * from peminjaman where ID_Anggota = '"+IdAnggota.getText()+"'order by ID_Peminjaman asc";
            Connection konek= new koneksi_mysql().getConnection();
            Statement stat = konek.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            int terpinjam = 0 ;
            while(hasil.next()){ 
                terpinjam++;
            }
            hasil.close();
                
            if(terpinjam<3){
                sql = "Select ID_Peminjaman from peminjaman order by ID_Peminjaman asc";
                konek= new koneksi_mysql().getConnection();
                stat = konek.createStatement();
                hasil = stat.executeQuery(sql);
                int ID_Anggota = 0 ;
                while(hasil.next()){ 
                    ID_Anggota = hasil.getInt("ID_Peminjaman");
                }
                hasil.close();
            
                    ID_Anggota++;
                    Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/perpus","root","");
            
                    koneksi.createStatement().execute("insert into peminjaman (`ID_Peminjaman`, `ID_Petugas`, `ID_Anggota`, `ID_Buku`, `Tanggal_Pinjam`, `Tanggal_Kembali`, `Tanggal_Pengembalian`, `Keterangan`, `Denda`) values('"+ID_Anggota+"','"+IdPetugas.getText()+"','"+IdAnggota.getText()+"','"+IdBuku.getText()+"','"+Integer.toString(pinjam.getTahun())+"-"+Integer.toString(pinjam.getBulan())+"-"+Integer.toString(pinjam.getHari())+"','"+Integer.toString(kembali.getTahun())+"-"+Integer.toString(kembali.getBulan())+"-"+Integer.toString(kembali.getHari())+"','0001-01-01','PINJAM','0')");
                jLabel12.setText("Tanggal Kembali      : "+kembali.getHari()+"-"+kembali.getBulan()+"-"+kembali.getTahun());
                jLabel2.setText("Data telah tersimpan");
            }else{
                jLabel2.setText("<html>Anggota sudah meminjam melebihi batas peminjaman<br>(maks. 3 buku)<html>");
            }
        } catch (Exception e)
           {
               System.out.println(e);
               JOptionPane.showMessageDialog(rootPane,"Maaf Data Yang Anda Masukkan Salah");
           }
    }//GEN-LAST:event_BtnSimpanDataActionPerformed

    private void BulanPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BulanPinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BulanPinjamActionPerformed

    private void TahunPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TahunPinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TahunPinjamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fromPinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fromPinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fromPinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fromPinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                fromPinjam dialog = new fromPinjam(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSimpanData;
    private javax.swing.JTextField BulanPinjam;
    private javax.swing.JTextField IdAnggota;
    private javax.swing.JTextField IdBuku;
    private javax.swing.JTextField IdPetugas;
    private javax.swing.JTextField TahunPinjam;
    private javax.swing.JTextField TanggalPinjam;
    private javax.swing.JTable id_Anggota;
    private javax.swing.JTable id_buku;
    private javax.swing.JTable id_petugas;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
