/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpus_apl;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.lang.Object;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.text.DateFormat;
import java.text.ParseException;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KANIA
 */
public class fromKembali extends javax.swing.JDialog {

    /**
     * Creates new form fromKembali
     */
    
    private DefaultTableModel tabmode;
    
    private void tampil_Peminjaman(){
        Object[]baris={"ID Peminjaman","ID Petugas","ID Anggota","ID Buku","Tanggal Peminjaman"};
        tabmode = new DefaultTableModel(null,baris);
        jTable2.setModel(tabmode);
        String sql = ("Select ID_Peminjaman, ID_Petugas, ID_Anggota, ID_Buku, Tanggal_Pinjam from peminjaman WHERE peminjaman.ID_Anggota = '"+ID_Anggota.getText()+"' AND peminjaman.Keterangan <> 'DIKEMBALIKAN'");
      
        try{
            Connection konek= new koneksi_mysql().getConnection();
            Statement stat = konek.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){ 
                String ID_Peminjaman = hasil.getString("ID_Peminjaman");
                String ID_Petugas = hasil.getString("ID_Petugas");
                String ID_Anggota = hasil.getString("ID_Anggota");
                String ID_Buku = hasil.getString("ID_Buku");
                String Tanggal_Pinjam = hasil.getString("Tanggal_Pinjam");
                
                
                String[]data={ID_Peminjaman,ID_Petugas,ID_Anggota,ID_Buku,Tanggal_Pinjam};
                tabmode.addRow(data);
            }
            hasil.close();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Data Gagal", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
        }
    
    public fromKembali(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public long jarakHari(int D, int K) throws ParseException{
        //Tanggal TD = new Tanggal(TglD%100,(TglD/100)%100,TglD/10000);
        //  Tanggal TK = new Tanggal(TglK%100,(TglK/100)%100,TglK/10000);
        
        int Dh=D%100;
        int Db=(D/100)%100;
        int Dt=D/10000;
        String dateStart = new String(Db+"/"+Dh+"/"+Dt+" 00:00:00");
        
        int Kh=K%100;
        int Kb=(K/100)%100;
        int Kt=K/10000;
        String dateStop = new String(Kb+"/"+Kh+"/"+Kt+" 00:00:00");
        
        //HH converts hour in 24 hours format (0-23), day calculation
        SimpleDateFormat format = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");

        Date d1 = null;
        Date d2 = null;


            d1 = format.parse(dateStart);
            d2 = format.parse(dateStop);

            //in milliseconds
            long diff = d2.getTime() - d1.getTime();
            long hari = diff / (24 * 60 * 60 * 1000);
            if(hari<0){
                hari=0;
            }
            return hari;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ID_Pinjaman = new javax.swing.JTextField();
        ID_Anggota = new javax.swing.JTextField();
        Tanggal_Dikembalikan = new javax.swing.JTextField();
        BtSimpanKembali = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 153));

        jLabel1.setBackground(new java.awt.Color(153, 0, 0));
        jLabel1.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 251, 218));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FROM PENGEMBALIAN BUKU");
        jLabel1.setToolTipText("");
        jLabel1.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel2.setText("ID Peminjaman");

        jLabel3.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel3.setText("ID Anggota");

        jLabel5.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jLabel5.setText("Tanggal Dikembalikan");

        ID_Pinjaman.setBackground(new java.awt.Color(255, 255, 204));
        ID_Pinjaman.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        ID_Pinjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_PinjamanActionPerformed(evt);
            }
        });

        ID_Anggota.setBackground(new java.awt.Color(255, 255, 204));
        ID_Anggota.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N

        Tanggal_Dikembalikan.setBackground(new java.awt.Color(255, 255, 204));
        Tanggal_Dikembalikan.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N

        BtSimpanKembali.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        BtSimpanKembali.setText("Simpan");
        BtSimpanKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSimpanKembaliActionPerformed(evt);
            }
        });

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 204));

        jTable2.setBackground(new java.awt.Color(255, 255, 204));
        jTable2.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jTable2.setGridColor(new java.awt.Color(153, 0, 0));
        jScrollPane2.setViewportView(jTable2);

        jButton1.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ID_Anggota, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ID_Pinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Tanggal_Dikembalikan, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(BtSimpanKembali)))
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ID_Anggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ID_Pinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Tanggal_Dikembalikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtSimpanKembali)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtSimpanKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSimpanKembaliActionPerformed
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String sql = ("Select Tanggal_Kembali from peminjaman WHERE peminjaman.ID_Peminjaman = '"+ID_Pinjaman.getText()+"' AND peminjaman.ID_Anggota = '"+ID_Anggota.getText()+"'");
            Connection konek= new koneksi_mysql().getConnection();
            Statement stat = konek.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            String A = "0000-00-00";
            
            while(hasil.next()){ 
                A = hasil.getString("Tanggal_Kembali");
            }
            hasil.close();
            String B = Tanggal_Dikembalikan.getText();
            
            int TglD = Integer.parseInt(A.replaceAll("[\\D]",""));
            int TglK = Integer.parseInt(B.replaceAll("[\\D]",""));
            
            System.out.println(TglD);
            
            long denda = 1000*jarakHari(TglD,TglK);
            int d = (int) denda;
            System.out.println(d);
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/perpus","root","");
            koneksi.createStatement().execute("update peminjaman set `Tanggal_Pengembalian`='"+Tanggal_Dikembalikan.getText()+"',`Keterangan`='DIKEMBALIKAN',`Denda`= '"+d+"' WHERE peminjaman.ID_Peminjaman = '"+ID_Pinjaman.getText()+"' AND peminjaman.ID_Anggota = '"+ID_Anggota.getText()+"'");
            jLabel4.setText("Data sudah dimasukkan");
            if(d>0){
                jLabel6.setText("Anda dikenakan denda Rp."+d+" Karena terlambat "+jarakHari(TglD,TglK)+" hari");
            }
        } catch (Exception e){
               System.out.println(e);
               JOptionPane.showMessageDialog(rootPane,"Maaf Data Yang Anda Masukkan Salah");
           }
    }//GEN-LAST:event_BtSimpanKembaliActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        tampil_Peminjaman();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ID_PinjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_PinjamanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_PinjamanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fromKembali.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fromKembali.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fromKembali.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fromKembali.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                fromKembali dialog = new fromKembali(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtSimpanKembali;
    private javax.swing.JTextField ID_Anggota;
    private javax.swing.JTextField ID_Pinjaman;
    private javax.swing.JTextField Tanggal_Dikembalikan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
